version: "3.8"

services:
  
  user-electronic-dev:
    build:
      context: ./user
      dockerfile: Dockerfile
      target: dev
    image: tdat/user-electronic:dev
    container_name: user-electronic-dev
   

  user-electronic-prod:
    build:
      context: ./user
      dockerfile: Dockerfile
      target: prod
    image: tdat/user-electronic:prod
    container_name: user-electronic-prod

  catalog-electronic-dev:
    build:
      context: ./catalog
      dockerfile: Dockerfile
      target: dev
    image: tdat/catalog-electronic:dev
    container_name: catalog-electronic-dev
   

  catalog-electronic-prod:
    build:
      context: ./catalog
      dockerfile: Dockerfile
      target: prod
    image: tdat/catalog-electronic:prod
    container_name: catalog-electronic-prod

  order-electronic-dev:
    build:
      context: ./order
      dockerfile: Dockerfile
      target: dev
    image: tdat/order-electronic:dev
    container_name: order-electronic-dev
   

  order-electronic-prod:
    build:
      context: ./order
      dockerfile: Dockerfile
      target: prod
    image: tdat/order-electronic:prod
    container_name: order-electronic-prod

  frontendUser-electronic-dev:
    build:
      context: ./frontendUser
      dockerfile: Dockerfile
      target: dev
    image: tdat/frontenduser-electronic:dev
    container_name: frontendUser-electronic-dev
   

  frontendUser-electronic-prod:
    build:
      context: ./frontendUser
      dockerfile: Dockerfile
      target: prod
    image: tdat/frontenduser-electronic:prod
    container_name: frontendUser-electronic-prod

  payment-electronic-dev:
    build:
      context: ./payment
      dockerfile: Dockerfile
      target: dev
    image: tdat/payment-electronic:dev
    container_name: payment-electronic-dev
   

  payment-electronic-prod:
    build:
      context: ./payment
      dockerfile: Dockerfile
      target: prod
    image: tdat/payment-electronic:prod
    container_name: payment-electronic-prod

  nginx-electronic:
    container_name: nginx-electronic
    build:
      dockerfile: Dockerfile
      context: ./proxy
    image: tdat/nginx-electronic:latest # owasp/modsecurity-crs:nginx #reverse-proxy # owasp/modsecurity-crs:nginx 