version: "3.8"

services:
  zookeeper-electronic:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  
  kafka-electronic:
    image: confluentinc/cp-kafka:7.4.3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-electronic:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-electronic:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-electronic


  elasticsearch-electronic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - electronic-elastic:/usr/share/elasticsearch/data

  # mysql-kafka-catalog:
  #   image: mysql:8
  #   restart: always
  #   environment:
  #     MYSQL_USER: kafka_catalog
  #     MYSQL_PASSWORD: trongdat1335
  #     MYSQL_ROOT_PASSWORD: trongdatroot
  #     MYSQL_DATABASE: catalog
  #   ports:
  #     - "3302:3306"
  #   volumes:
  #     - mysql-kafka-catalog:/var/lib/mysql
  #   deploy:
  #     mode: replicated
  #     replicas: 1

  # mysql-kafka-order:
  #   image: mysql:8
  #   restart: always
  #   environment:
  #     MYSQL_USER: kafka_order
  #     MYSQL_PASSWORD: trongdat1335
  #     MYSQL_ROOT_PASSWORD: trongdatroot
  #     MYSQL_DATABASE: order
  #   ports:
  #     - "3303:3306"
  #   volumes:
  #     - mysql-kafka-order:/var/lib/mysql
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  # mysql-kafka-user:
  #   image: mysql:8
  #   restart: always
  #   environment:
  #     MYSQL_USER: kafka_user
  #     MYSQL_PASSWORD: trongdat1335
  #     MYSQL_ROOT_PASSWORD: trongdatroot
  #     MYSQL_DATABASE: user
  #   ports:
  #     - "3300:3306"
  #   volumes:
  #     - mysql-kafka-user:/var/lib/mysql
  #   deploy:
  #     mode: replicated
  #     replicas: 1


  user-electronic:
    image: tdat/user-electronic:dev
    restart: always
    deploy:
      replicas: 1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - kafka-electronic
    env_file:
      - ./user/.env
    expose:
      - 9000
    volumes:
      - .:/app/

  catalog-electronic:
    image: tdat/catalog-electronic:dev
    restart: always
    deploy:
      replicas: 1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - kafka-electronic
      - elasticsearch-electronic
    env_file:
      - ./catalog/.env
    expose:
      - 9001
    volumes:
      - .:/app/

  order-electronic:
    image: tdat/order-electronic:dev
    restart: always
    deploy:
      replicas: 1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - kafka-electronic
    env_file:
      - ./order/.env
    expose:
      - 9002
    volumes:
      - .:/app/

  payment-electronic:
    image: tdat/payment-electronic:dev
    restart: always
    deploy:
      replicas: 1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - kafka-electronic
    env_file:
      - ./payment/.env
    expose:
      - 9003
    volumes:
      - .:/app/


  nginx-electronic:
    container_name: nginx-electronic
    image: tdat/nginx-electronic:latest # owasp/modsecurity-crs:nginx #reverse-proxy # owasp/modsecurity-crs:nginx 
    depends_on:
      - user-electronic
      - catalog-electronic
      - order-electronic
      - payment-electronic
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx



  
volumes:
  # mysql-kafka-catalog:
  #   external: true
  # mysql-kafka-order:
  #   external: true
  # mysql-kafka-user:
  #   external: true
  electronic-elastic:
    driver: local