version: "3.8"

services:
  mysql-kafka-catalog:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: kafka_catalog
      MYSQL_PASSWORD: trongdat1335
      MYSQL_ROOT_PASSWORD: trongdatroot
      MYSQL_DATABASE: catalog
    ports:
      - "3302:3306"
    volumes:
      - mysql-kafka-catalog:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1

  mysql-kafka-order:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: kafka_order
      MYSQL_PASSWORD: trongdat1335
      MYSQL_ROOT_PASSWORD: trongdatroot
      MYSQL_DATABASE: order
    ports:
      - "3303:3306"
    volumes:
      - mysql-kafka-order:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
  mysql-kafka-user:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: kafka_user
      MYSQL_PASSWORD: trongdat1335
      MYSQL_ROOT_PASSWORD: trongdatroot
      MYSQL_DATABASE: user
    ports:
      - "3300:3306"
    volumes:
      - mysql-kafka-user:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
  
volumes:
  mysql-kafka-catalog:
    external: true
  mysql-kafka-order:
    external: true
  mysql-kafka-user:
    external: true